coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 0%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 0%
        if_ci_failed: error

comment:
  require_changes: false
  require_base: false
  require_head: true
