package com.salesforce.multicloudj.blob.gcp.util;

import com.github.tomakehurst.wiremock.common.FileSource;
import com.github.tomakehurst.wiremock.extension.Parameters;
import com.github.tomakehurst.wiremock.extension.StubMappingTransformer;
import com.github.tomakehurst.wiremock.matching.ContentPattern;
import com.github.tomakehurst.wiremock.matching.RequestPattern;
import com.github.tomakehurst.wiremock.matching.RequestPatternBuilder;
import com.github.tomakehurst.wiremock.stubbing.StubMapping;

import java.util.List;
import java.util.regex.Pattern;

import static com.github.tomakehurst.wiremock.client.WireMock.urlMatching;

/**
 * Transformer that replaces exact upload_id parameter values in resumable upload URLs
 * with regex patterns to allow flexible matching during replay.
 *
 * This handles the dynamic upload_id values generated by GCP Storage for resumable uploads.
 * The transformer converts exact URL matches to URL pattern matches by replacing
 * the exact upload_id value with a regex pattern.
 */
public class ResumableUploadIdTransformer extends StubMappingTransformer {

    // Pattern to match upload_id parameter: upload_id=<value>
    // The value can contain alphanumeric, dash, underscore, and equals characters
    private static final Pattern UPLOAD_ID_PATTERN = Pattern.compile("upload_id=[A-Za-z0-9_-]+");
    private static final String UPLOAD_ID_REPLACEMENT = "upload_id=[^&]+";

    @Override
    public StubMapping transform(StubMapping stubMapping, FileSource files, Parameters parameters) {
        RequestPattern requestPattern = stubMapping.getRequest();
        String url = requestPattern.getUrl();
        String urlPattern = requestPattern.getUrlPattern();

        // Check if this is a resumable upload request (PUT or POST with uploadType=resumable)
        boolean isResumableUpload = (url != null && url.contains("uploadType=resumable")) ||
                                   (urlPattern != null && urlPattern.contains("uploadType=resumable"));

        if (isResumableUpload) {
            String transformedPattern = null;

            if (url != null && url.contains("upload_id=")) {
                // Replace exact upload_id value with regex pattern and escape special characters
                transformedPattern = escapeUrlForRegex(url);
            } else if (urlPattern != null && urlPattern.contains("upload_id=")) {
                // If it's already a pattern, ensure upload_id is flexible
                transformedPattern = UPLOAD_ID_PATTERN.matcher(urlPattern).replaceAll(UPLOAD_ID_REPLACEMENT);
            }

            if (transformedPattern != null) {
                // Rebuild the RequestPattern with the transformed URL pattern
                RequestPatternBuilder builder = RequestPatternBuilder.newRequestPattern(
                    requestPattern.getMethod(), 
                    urlMatching(transformedPattern)
                );
                
                // Copy body patterns if they exist
                List<ContentPattern<?>> bodyPatterns = requestPattern.getBodyPatterns();
                if (bodyPatterns != null && !bodyPatterns.isEmpty()) {
                    for (ContentPattern<?> pattern : bodyPatterns) {
                        builder.withRequestBody(pattern);
                    }
                }
                
                RequestPattern newRequestPattern = builder.build();
                
                // Create a new StubMapping with the modified RequestPattern
                StubMapping newStubMapping = new StubMapping(newRequestPattern, stubMapping.getResponse());
                // Copy all other properties from the original stub
                newStubMapping.setId(stubMapping.getId());
                newStubMapping.setPriority(stubMapping.getPriority());
                newStubMapping.setScenarioName(stubMapping.getScenarioName());
                newStubMapping.setRequiredScenarioState(stubMapping.getRequiredScenarioState());
                newStubMapping.setNewScenarioState(stubMapping.getNewScenarioState());
                newStubMapping.setPersistent(stubMapping.isPersistent());
                return newStubMapping;
            }
        }

        return stubMapping;
    }

    /**
     * Escapes special regex characters in the URL while preserving our regex pattern for upload_id.
     * WireMock regex patterns need special characters escaped, except for our intentional regex pattern.
     */
    private String escapeUrlForRegex(String url) {
        // Replace upload_id value with regex pattern first
        String withRegex = UPLOAD_ID_PATTERN.matcher(url).replaceAll(UPLOAD_ID_REPLACEMENT);
        
        // Now escape special regex characters, but preserve our upload_id=[^&]+ pattern
        // We'll escape everything except the upload_id pattern we just inserted
        StringBuilder result = new StringBuilder();
        int uploadIdIndex = withRegex.indexOf("upload_id=[^&]+");
        
        if (uploadIdIndex >= 0) {
            // Escape the part before upload_id pattern
            String before = withRegex.substring(0, uploadIdIndex);
            result.append(escapeRegexSpecialChars(before));
            
            // Keep the upload_id regex pattern as-is
            result.append("upload_id=[^&]+");
            
            // Escape the part after upload_id pattern
            String after = withRegex.substring(uploadIdIndex + "upload_id=[^&]+".length());
            result.append(escapeRegexSpecialChars(after));
        } else {
            // No upload_id pattern found, escape the whole URL
            result.append(escapeRegexSpecialChars(withRegex));
        }
        
        return result.toString();
    }
    
    /**
     * Escapes special regex characters that need to be literal in the URL pattern.
     */
    private String escapeRegexSpecialChars(String str) {
        return str.replaceAll("([\\\\^$\\[\\]{}()*+?.|])", "\\\\$1");
    }


    @Override
    public String getName() {
        return "resumable-upload-id-transformer";
    }

    @Override
    public boolean applyGlobally() {
        return true;
    }
}
