name: Java CI with Maven and Codecov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven and run tests
        run: mvn -B clean test

      - name: Generate Site with Reports
        run: mvn -B site:site -DskipTests -N

      - name: Run JaCoCo Report Aggregate
        run: mvn -B jacoco:report-aggregate -DskipTests

      - name: Debug - Check JaCoCo Report Location
        run: |
          echo "Checking for JaCoCo reports..."
          find ./target -name "jacoco.xml" || echo "No JaCoCo XML reports found"
          echo "---"
          head -n 20 ./target/site/jacoco-aggregate/jacoco.xml || echo "Report missing or empty"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./target/site/jacoco-aggregate/
          flags: unittests
          verbose: true
          working-directory: .
